on:
  push:
  pull_request:
  schedule:
    - cron: '13 15 * * *'
permissions: { }
jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        rust_toolchain:
          - 'stable'
          - 'beta'
          - 'nightly'
          - '1.85.1'
        target:
          - os: 'ubuntu-24.04-arm'
            triple: 'aarch64-unknown-linux-gnu'
          - os: 'ubuntu-24.04'
            triple: 'x86_64-unknown-linux-gnu'
          - os: 'macos-15-intel'
            triple: 'x86_64-apple-darwin'
          - os: 'macos-15'
            triple: 'aarch64-apple-darwin'
          - os: 'windows-2025'
            triple: 'x86_64-pc-windows-msvc'
    continue-on-error: ${{ matrix.rust_toolchain == 'nightly' }}
    runs-on: ${{ matrix.target.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
        with:
          toolchain: ${{ matrix.rust_toolchain }}
          target: ${{ matrix.target.triple }}
          components: clippy

      - name: Build Workspace
        run: |
          rustc --version
          cargo build --workspace --no-default-features
          cargo build --workspace
          cargo test --workspace --no-run

      - name: Test Workspace
        run: |
          cargo test --workspace

      - name: Run Clippy
        if: ${{ matrix.rust_toolchain == 'stable' || matrix.rust_toolchain == 'beta' }}
        run: |
          cargo clippy --workspace --all-targets --all-features
