on:
  push:
    branches-ignore:
      - 'ci-test'
      - 'dependabot/**'
    tags-ignore:
      - '**'
  pull_request:
  schedule:
    - cron: '13 15 * * *'
  workflow_dispatch:
jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        rust_toolchain:
          - 'stable'
          - 'beta'
          - 'nightly'
          - '1.85.1'
        target:
          - os: 'ubuntu-22.04'
            triple: 'x86_64-unknown-linux-gnu'
          - os: 'macos-13'
            triple: 'x86_64-apple-darwin'
          - os: 'macos-15'
            triple: 'aarch64-apple-darwin'
          - os: 'windows-2022'
            triple: 'x86_64-pc-windows-msvc'
    continue-on-error: ${{ matrix.rust_toolchain == 'nightly' }}
    runs-on: ${{ matrix.target.os }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b # v1
        with:
          toolchain: ${{ matrix.rust_toolchain }}
          target: ${{ matrix.target.triple }}
          components: clippy

      - name: Build Workspace
        run: |
          rustc --version
          cargo build --workspace --no-default-features
          cargo build --workspace
          cargo test --workspace --no-run

      - name: Test Workspace
        run: |
          cargo test --workspace

      - uses: actions-rs/clippy@master
        if: ${{ matrix.rust_toolchain == 'stable' || matrix.rust_toolchain == 'beta' }}
        with:
          args: --workspace
